bsabrowserPath: "I:\\Modding\\Fallout 76\\tools\\BSA Browser Portable-1756-1-16-0-1647634108\\"
rabcdasmPath: "I:\\Modding\\Fallout 76\\RABCDAsm_v1.18\\"
archivePath: "E:\\SteamLibrary\\steamapps\\common\\Fallout76\\Data\\SeventySix - Interface.ba2"
templatePath: "./config/templates"
patches:
  securetrade:
    modDir: "I:\\Modding\\Fallout 76\\InventOmatic\\src\\InventOmaticStash"
    workingDir: "loader\\generated"
    swfPath: "interface/securetrade.swf"
    targetPatchFile: "interface/securetrade-0.abc.patched"
    targetDir: "release"
    edits:
      SecureTrade:
        - name: "injectSFE"
        - name: "injectLoader"
          params:
            modFile: "InventOmaticStash.swf"
            template: "modloader_callback.asasm"
        - name: "makePackagePrivate"
          params:
            fieldName: "ButtonHintDataV"
        - name: "makePackagePrivate"
          params:
            fieldName: "ButtonHintBar_mc"
      "Shared.AS3.QuantityMenu":
        - name: "patchQuantityMenu"