bsabrowserPath: "I:\\Modding\\Fallout 76\\tools\\BSA Browser Portable-1756-1-16-0-1647634108\\"
rabcdasmPath: "I:\\Modding\\Fallout 76\\RABCDAsm_v1.18\\"
archivePath: "E:\\SteamLibrary\\steamapps\\common\\Fallout76\\Data\\SeventySix - Interface.ba2"
templatePath: "./config/templates"
patches:
  securetrade:
    modDir: "I:\\Modding\\Fallout 76\\InventOmatic\\src\\InventOmaticPipboy"
    workingDir: "loader\\generated"
    swfPath: "interface/pipboy_invpage.swf"
    targetPatchFile: "interface/pipboy_invpage-0.abc.patched"
    targetDir: "release"
    edits:
      Pipboy_InvPage:
        - name: "injectSFE"
        - name: "injectLoader"
          params:
            modFile: "InventOmaticPipboy.swf"
            template: "modloader_callback.asasm"